version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    # ports:
    #   - "9090:9090" # toggle for testing
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/secrets/prometheus_password:/etc/prometheus/secrets/prometheus_password:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_AUTH_ANONYMOUS_ENABLED=true          # Enable anonymous access
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer       # Read-only permissions
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_PASSWORD_RESET=true
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

  nginx:
    # Deliberately chosen with vulnerabilities to test dependency tools
    image: nginx:1.28.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount certs from host
    depends_on:
      - grafana
      - prometheus
    restart: unless-stopped

volumes:
  grafana-storage:
  prometheus-data:
