global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'mini-farm-tracker'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['api.mini-farm-tracker.io']
    # enable_compression: false
    basic_auth:
      username: 'prometheus'
      password_file: /etc/prometheus/secrets/prometheus_password